spring:
  application:
    name: enjoytrip_07_kjw_lgb
    
  #dataSouce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    
server:
  port: 80
  
#mybatis
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.enjoytrip.*.dto
  
logging:
  level:
    root: info
    com.enjoytrip: debug